proxy_timeout_secs = 60
response_timeout_secs = 60
# own_ip = "91.235.33.151"
echo_service_url = "https://bikuzin.baza-winner.ru/echo"
own_ip_fresh_duration_secs = 10
same_time_proxy_check_max_count = 100
same_time_request_max_count = 100
proxy_rest_duration_millis = 2000
success_start_count = 3
success_max_count = 6
sources = [
    "https://raw.githubusercontent.com/fate0/proxylist/master/proxy.list", 
    "https://raw.githubusercontent.com/a2u/free-proxy-list/master/free-proxy-list.txt", 
    "http://rootjazz.com/proxies/proxies.txt", 
    "https://socks-proxy.net/", 
    "http://online-proxy.ru/", 
]
