version: '3'

services:

    proj:
        container_name: ${BW_PROJ_NAME}-proj
        image: bazawinner/dev-${BW_PROJ_NAME}-proj:${BW_DEV_PROJ_VERSION}
        entrypoint: ["docker-entrypoint.sh"]
        tty: true
        environment:
            - TZ=Europe/Moscow

            - BW_PROJ_NAME
            - RUST_LOG=info
        volumes:
            - ./dev/proj/sh:/sh
            - ./src:/home/rust/src
            - ./out:/out
            - ./dev/proj/cargo-git/:/home/rust/.cargo/git
            - ./dev/proj/cargo-registry/:/home/rust/.cargo/registry
            - ./dev/proj/cargo-target/:/home/rust/src/target
        depends_on:
            - proxy

    proxy:
        container_name: ${BW_PROJ_NAME}-proxy
        image: bazawinner/dev-${BW_PROJ_NAME}-proj:${BW_DEV_PROJ_VERSION}
        entrypoint: ["docker-entrypoint.sh"]
        tty: true
        environment:
            - TZ=Europe/Moscow

            - BW_PROJ_NAME
            - RUST_LOG=info
        volumes:
            - ./dev/proj/sh:/sh
            - ./src/proxy/src:/home/rust/src
            - ./dev/proxy/cargo-git/:/home/rust/.cargo/git
            - ./dev/proxy/cargo-registry/:/home/rust/.cargo/registry
            - ./dev/proxy/cargo-target/:/home/rust/src/target
        ports:
            - $BW_DEV_PROXY_PORT:8000
        depends_on:
            - rmq

    rmq:
        container_name: ${BW_PROJ_NAME}-rmq
        image: rabbitmq:3.8.4-management
        environment:
            RABBITMQ_DEFAULT_USER: rmq
            RABBITMQ_DEFAULT_PASS: rmq
        ports:
            - $BW_DEV_RABBITMQ_PORT:5672
            - $BW_DEV_RABBITMQ_PORT_MANAGEMENT:15672

    auth:
        container_name: ${BW_PROJ_NAME}-auth
        image: bazawinner/dev-${BW_PROJ_NAME}-auth:${BW_DEV_AUTH_VERSION}
        entrypoint: ["docker-entrypoint.sh"]
        tty: true
        environment:
            - PATH=/sh:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            - TZ=Europe/Moscow

            - BW_PROJ_NAME
            - BW_DEV_AUTH_PORT
        volumes:
            - ./dev/auth/sh:/sh
            - ./dev/auth/src:/proj/src
            - ./dev/auth/out:/proj/out
        ports:
            - $BW_DEV_AUTH_PORT:3000
