version: '3'

services:

    proj:
        container_name: prod-${BW_PROJ_NAME}-proj
        image: bazawinner/prod-${BW_PROJ_NAME}-proj:${BW_PROD_PROJ_VERSION}
        tty: true
        environment:
            - TZ=Europe/Moscow
            - RUST_LOG=warn
            - AVITO_COUNT_LIMIT=4000
            - AVITO_AUTH=$BW_AVITO_AUTH
            - AVITO_PARAMS=categoryId=9&locationId=637640&searchRadius=100&privateOnly=1&sort=date&owner[]=private
            - BW_RABBITMQ_USER=$BW_PROD_RABBITMQ_USER
            - BW_RABBITMQ_PASS=$BW_PROD_RABBITMQ_PASS
            - BW_RABBITMQ_HOST=$BW_PROD_RABBITMQ_HOST
            - BW_RABBITMQ_PORT=$BW_PROD_RABBITMQ_PORT
            - BW_RABBITMQ_VHOST=$BW_PROD_RABBITMQ_VHOST
        volumes:
            - ./out:/out

