version: '3'

services:

    proj:
        container_name: prod-${BW_PROJ_NAME}-proj
        image: bazawinner/prod-${BW_PROJ_NAME}-proj:${BW_PROD_PROJ_VERSION}
        tty: true
        environment:
            - TZ=Europe/Moscow
            - RUST_LOG=info
        volumes:
            - $BW_HOST_CNF_DIR:/cnf
            - $BW_HOST_OUT_DIR:/out

