[workspace]
default-members = [ "scan", "proxy_checker" ]
members = [ 
    "term", 
    "env", 
    "arrange_millis", 
    "auth", "diaps", 
    "diap_store", 
    "ids", 
    "id_store", 
    "cards", 
    "autocatalog",
    "scan", 
    "collect",
    "to_csv",
    "proxy_checker",
]
# [targt.x86_64-unknown-linux-musl]
# linker = "x86_64-linux-musl-gcc"

